# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49cae750eebfdce8e2c5551171bc37c2e6206b9a1ef8cfab595fa57a948c436911a3db42cd48aae0b6996999f2c022bab69cc0877a437a35e597685d385e60b6

test:
  secret_key_base: d99cf097b1b690ba65e10ba8239dd06abd4c5b8786334e9e634e9c8b1c7ec00972b7a29c36346e0e2665448967109fe89d179deeacaaabeb2b5b75f7153c6ed1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
